# Generated by Django 4.0.3 on 2022-03-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_alter_pizza_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='thumbnail_url',
        ),
    ]
